macro(erl_config_qt6)
    set(components ${ARGN})
    if (NOT components)
        message(FATAL_ERROR "No components specified for erl_config_qt6")
    endif ()
    erl_find_package(PACKAGE Qt6 COMPONENTS ${components} REQUIRED)

    # set(CMAKE_AUTOMOC ON)
    # add_compile_definitions(QT_NO_KEYWORDS)
    # set_target_properties(my_target PROPERTIES AUTOMOC ON)
    foreach (component IN LISTS components)
        erl_collect_library_dependencies(Qt6::${component} includes libs)
        list(APPEND Qt6_INCLUDE_DIRS ${includes})
        list(APPEND Qt6_LIBRARIES ${libs})
    endforeach ()
    list(REMOVE_DUPLICATES Qt6_INCLUDE_DIRS)
    list(REMOVE_DUPLICATES Qt6_LIBRARIES)
    message(STATUS "Qt6_INCLUDE_DIRS: ${Qt6_INCLUDE_DIRS}")
    message(STATUS "Qt6_LIBRARIES: ${Qt6_LIBRARIES}")

    unset(includes)
    unset(libs)
    unset(components)
endmacro()
